# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- master

pool:
  vmImage: ubuntu-latest

steps:
- task: AzureResourceManagerTemplateDeployment@3
  inputs:
    deploymentScope: 'Resource Group'
    azureResourceManagerConnection: 'AzureRmPipeline-conn'
    subscriptionId: '5c91123c-a673-4557-8f9c-185b6c21b9ec'
    action: 'Create Or Update Resource Group'
    resourceGroupName: 'AzureRmPipeline-rg'
    location: 'Central US'
    templateLocation: 'URL of the file'
    csmFileLink: 'https://raw.githubusercontent.com/vanamteja1995/AzureRmPipeline/master/CreateWebApp/azuredeploy.json'
    overrideParameters: '-projectName AzureRmPipeline'
    deploymentMode: 'Incremental'
    deploymentName: 'DeployPipelineTemplate'
